var strVar1="";
strVar1 += "  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;background: rgb(255, 255, 255);\" width=\"100%\">";
strVar1 += "    <tbody>";
strVar1 += "      <tr>";
strVar1 += "        <td>";
strVar1 += "";
strVar1 += "  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "    <tbody>";
strVar1 += "      <tr>";
strVar1 += "        <td>";
strVar1 += "          <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar1 += "        <\/td>";
strVar1 += "      <\/tr>";
strVar1 += "    <\/tbody>";
strVar1 += "  <\/table>";
strVar1 += "";
strVar1 += "  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; border:1px solid #cccccc;\" width=\"600\">";
strVar1 += "    <tbody>";
strVar1 += "      <tr>";
strVar1 += "        <td>";
strVar1 += "";
strVar1 += "          <table align=\"center\" bgcolor=\"#FFFFFF\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td align=\"left\" valign=\"middle\" width=\"600\">";
strVar1 += "                  <a href=\"http:\/\/www.panerai.com\/fr\/\" target=\"_blank\">";
strVar1 += "                    <img alt=\"Claravista\" border=\"0\" src=\"http:\/\/www.claravista.fr\/images\/logo_claravista.png\" style=\"display:block; outline: 0;\" title=\"\" width=\"250\" \/>";
strVar1 += "                  <\/a>";
strVar1 += "                <\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "";
strVar1 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; background: white;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td width=\"20\">&nbsp;<\/td>";
strVar1 += "                <td width=\"560\" align=\"left\">";
strVar1 += "                  <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:13px;color:#black;\">&nbsp;<br\/>";
strVar1 += "                    Dear $civilite$ $prenom$,<br\/>";
strVar1 += "                    <br\/>";
strVar1 += "                    Thank you for your visit in our boutique <b>$nom_boutique$<\/b>. We hope that you had a pleasant moment with us.<br\/>";
strVar1 += "                    <br\/>";
strVar1 += "                    Below, you will find further information about the product(s) you were interested in.<br\/>";
strVar1 += "                    Please, feel free to contact us if you need other information or if you would like to take an appointment with us.<br\/>";
strVar1 += "                    <br\/>";
strVar1 += "                    We look forward to seeing you again<br\/>";
strVar1 += "                    <br\/>";
strVar1 += "                    Yours sincerly<br\/>";
strVar1 += "                    <p style=\"text-align: right; font-weight:bold;\">";
strVar1 += "                      $SA_signature$<br\/>";
strVar1 += "                      Sales Assistant of Claravista";
strVar1 += "                    <\/p>";
strVar1 += "                    &nbsp;<br\/>";
strVar1 += "                  <\/font>";
strVar1 += "                <\/td>";
strVar1 += "                <td width=\"20\">&nbsp;<\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "";
strVar1 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td>";
strVar1 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar1 += "                <\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "";
strVar1 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td align=\"center\" style=\"text-align:center\">";
strVar1 += "                  <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:18px;color:#999999; font-weight:bold;\">";
strVar1 += "                    $nom_produit_1$";
strVar1 += "                  <\/font>";
strVar1 += "                <\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "";
strVar1 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td>";
strVar1 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar1 += "                <\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "";
strVar1 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td align=\"center\" style=\"text-align:center\">";
strVar1 += "                  <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:16px;color:#666666; font-weight:bold;\">";
strVar1 += "                    $ref_produit_1$";
strVar1 += "                  <\/font>";
strVar1 += "                <\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "";
strVar1 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td>";
strVar1 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar1 += "                <\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "";
strVar1 += "           <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td>";
strVar1 += "                  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "                    <tbody>";
strVar1 += "                      <td width=\"250\">";
strVar1 += "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"250\">";
strVar1 += "                          <tbody>";
strVar1 += "                            <tr>";
strVar1 += "                              <td width=\"25\">&nbsp;<\/td>";
strVar1 += "                              <td width=\"200\">";
strVar1 += "                                <img alt=\"\" border=\"0\" src=\"$produit_img_url_1$\" style=\"display:block;\" width=\"200\" \/>";
strVar1 += "                                <br \/>&nbsp;";
strVar1 += "                              <\/td>";
strVar1 += "                              <td width=\"20\">&nbsp;<\/td>";
strVar1 += "                            <\/tr>";
strVar1 += "                          <\/tbody>";
strVar1 += "                        <\/table>";
strVar1 += "                      <\/td>";
strVar1 += "                      <td width=\"350\" valign=\"top\">";
strVar1 += "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"350\">";
strVar1 += "                          <tbody>";
strVar1 += "                            <tr>";
strVar1 += "                              <td width=\"15\">&nbsp;<\/td>";
strVar1 += "                              <td width=\"320\">";
strVar1 += "                                <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:12px;color:#999999;\">";
strVar1 += "                                  $produit_descriptif_1$";
strVar1 += "                                  <p style=\"color:#666666; font-weigh:bold; font-size:14px;\">$produit_prix_1$ €<\/p>";
strVar1 += "                                <\/font>";
strVar1 += "                              <\/td>";
strVar1 += "                              <td width=\"15\">&nbsp;<\/td>";
strVar1 += "                            <\/tr>";
strVar1 += "                          <\/tbody>";
strVar1 += "                        <\/table>";
strVar1 += "                      <\/td>";
strVar1 += "                    <\/tbody>";
strVar1 += "                  <\/table>";
strVar1 += "                <\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "         ";
strVar1 += "";
strVar1 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td>";
strVar1 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar1 += "                <\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "";
strVar1 += "          <!--FOOTER-->";
strVar1 += "";
strVar1 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; background: white;\" width=\"600\">";
strVar1 += "            <tbody>";
strVar1 += "              <tr>";
strVar1 += "                <td width=\"600\">";
strVar1 += "                  <p style=\"text-align:center; color: black; font-size:12px;\">";
strVar1 += "                    19-21 RUE POISSONNIÈRE,<br \/>";
strVar1 += "                    75002, PARIS<br \/>";
strVar1 += "                    +33 1 85 08 21 21<br \/>";
strVar1 += "                    &nbsp;";
strVar1 += "                  <\/p>";
strVar1 += "                <\/td>";
strVar1 += "              <\/tr>";
strVar1 += "            <\/tbody>";
strVar1 += "          <\/table>";
strVar1 += "        <\/td>";
strVar1 += "      <\/tr>";
strVar1 += "    <\/tbody>";
strVar1 += "  <\/table>";
strVar1 += "";
strVar1 += "  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar1 += "    <tbody>";
strVar1 += "      <tr>";
strVar1 += "        <td>";
strVar1 += "          <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar1 += "        <\/td>";
strVar1 += "      <\/tr>";
strVar1 += "    <\/tbody>";
strVar1 += "  <\/table>";
strVar1 += "        <\/td>";
strVar1 += "      <\/tr>";
strVar1 += "    <\/tbody>";
strVar1 += "  <\/table>";
strVar1 += "";

var strVar2="";
strVar1 += "  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"100%\">";
strVar1 += "    <tbody>";
strVar1 += "      <tr>";
strVar1 += "        <td>";
strVar1 += "";
strVar2 += "  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "    <tbody>";
strVar2 += "      <tr>";
strVar2 += "        <td>";
strVar2 += "          <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar2 += "        <\/td>";
strVar2 += "      <\/tr>";
strVar2 += "    <\/tbody>";
strVar2 += "  <\/table>";
strVar2 += "";
strVar2 += "  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; border:1px solid #cccccc;\" width=\"600\">";
strVar2 += "    <tbody>";
strVar2 += "      <tr>";
strVar2 += "        <td>";
strVar2 += "";
strVar2 += "          <table align=\"center\" bgcolor=\"#FFFFFF\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td align=\"left\" valign=\"middle\" width=\"600\">";
strVar2 += "                  <a href=\"http:\/\/www.panerai.com\/fr\/\" target=\"_blank\">";
strVar2 += "                    <img alt=\"Claravista\" border=\"0\" src=\"http:\/\/www.claravista.fr\/images\/logo_claravista.png\" style=\"display:block; outline:0;\" title=\"\" width=\"250\" \/>";
strVar2 += "                  <\/a>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; background: white;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td width=\"20\">&nbsp;<\/td>";
strVar2 += "                <td width=\"560\" align=\"left\">";
strVar2 += "                  <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:13px;color:#black;\">&nbsp;<br\/>";
strVar2 += "                    Dear $civilite$ $prenom$,<br\/>";
strVar2 += "                    <br\/>";
strVar2 += "                    Thank you for your visit in our boutique <b>$nom_boutique$<\/b>. We hope that you had a pleasant moment with us.<br\/>";
strVar2 += "                    <br\/>";
strVar2 += "                    Below, you will find further information about the product(s) you were interested in.<br\/>";
strVar2 += "                    Please, feel free to contact us if you need other information or if you would like to take an appointment with us.<br\/>";
strVar2 += "                    <br\/>";
strVar2 += "                    We look forward to seeing you again<br\/>";
strVar2 += "                    <br\/>";
strVar2 += "                    Yours sincerly<br\/>";
strVar2 += "                    <p style=\"text-align: right; font-weight:bold;\">";
strVar2 += "                      $SA_signature$<br\/>";
strVar2 += "                      Sales Assistant of Claravista";
strVar2 += "                    <\/p>";
strVar2 += "                    &nbsp;<br\/>";
strVar2 += "                  <\/font>";
strVar2 += "                <\/td>";
strVar2 += "                <td width=\"20\">&nbsp;<\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td>";
strVar2 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td align=\"center\" style=\"text-align:center\">";
strVar2 += "                  <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:18px;color:#999999; font-weight:bold;\">";
strVar2 += "                    $nom_produit_1$";
strVar2 += "                  <\/font>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td>";
strVar2 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td align=\"center\" style=\"text-align:center\">";
strVar2 += "                  <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:16px;color:#666666; font-weight:bold;\">";
strVar2 += "                    $ref_produit_1$";
strVar2 += "                  <\/font>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td>";
strVar2 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "           <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td>";
strVar2 += "                  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "                    <tbody>";
strVar2 += "                      <td width=\"250\">";
strVar2 += "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"250\">";
strVar2 += "                          <tbody>";
strVar2 += "                            <tr>";
strVar2 += "                              <td width=\"25\">&nbsp;<\/td>";
strVar2 += "                              <td width=\"200\">";
strVar2 += "                                <img alt=\"\" border=\"0\" src=\"$produit_img_url_1$\" style=\"display:block;\" width=\"200\" \/>";
strVar2 += "                                <br \/>&nbsp;";
strVar2 += "                              <\/td>";
strVar2 += "                              <td width=\"20\">&nbsp;<\/td>";
strVar2 += "                            <\/tr>";
strVar2 += "                          <\/tbody>";
strVar2 += "                        <\/table>";
strVar2 += "                      <\/td>";
strVar2 += "                      <td width=\"350\" valign=\"top\">";
strVar2 += "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"350\">";
strVar2 += "                          <tbody>";
strVar2 += "                            <tr>";
strVar2 += "                              <td width=\"15\">&nbsp;<\/td>";
strVar2 += "                              <td width=\"320\">";
strVar2 += "                                <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:12px;color:#CCCCCC;\">";
strVar2 += "                                  $produit_descriptif_1$";
strVar2 += "                                  <p style=\"color:#AAAAAA; font-weigh:bold; font-size:14px;\">$produit_prix_1$ €<\/p>";
strVar2 += "                                <\/font>";
strVar2 += "                              <\/td>";
strVar2 += "                              <td width=\"15\">&nbsp;<\/td>";
strVar2 += "                            <\/tr>";
strVar2 += "                          <\/tbody>";
strVar2 += "                        <\/table>";
strVar2 += "                      <\/td>";
strVar2 += "                    <\/tbody>";
strVar2 += "                  <\/table>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "         ";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td>";
strVar2 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td align=\"center\" style=\"text-align:center\">";
strVar2 += "                  <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:18px;color:#999999; font-weight:bold;\">";
strVar2 += "                    $nom_produit_2$";
strVar2 += "                  <\/font>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td>";
strVar2 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td align=\"center\" style=\"text-align:center\">";
strVar2 += "                  <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:16px;color:#666666; font-weight:bold;\">";
strVar2 += "                    $ref_produit_2$";
strVar2 += "                  <\/font>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td>";
strVar2 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "           <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td>";
strVar2 += "                  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "                    <tbody>";
strVar2 += "                      <td width=\"250\">";
strVar2 += "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"250\">";
strVar2 += "                          <tbody>";
strVar2 += "                            <tr>";
strVar2 += "                              <td width=\"25\">&nbsp;<\/td>";
strVar2 += "                              <td width=\"200\">";
strVar2 += "                                <img alt=\"\" border=\"0\" src=\"$produit_img_url_2$\" style=\"display:block;\" width=\"200\" \/>";
strVar2 += "                                <br \/>&nbsp;";
strVar2 += "                              <\/td>";
strVar2 += "                              <td width=\"20\">&nbsp;<\/td>";
strVar2 += "                            <\/tr>";
strVar2 += "                          <\/tbody>";
strVar2 += "                        <\/table>";
strVar2 += "                      <\/td>";
strVar2 += "                      <td width=\"350\" valign=\"top\">";
strVar2 += "                        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"350\">";
strVar2 += "                          <tbody>";
strVar2 += "                            <tr>";
strVar2 += "                              <td width=\"15\">&nbsp;<\/td>";
strVar2 += "                              <td width=\"320\">";
strVar2 += "                                <font style=\"font-family:Verdana, Helvetica, sans-serif;font-size:12px;color:#999999;\">";
strVar2 += "                                  $produit_descriptif_2$";
strVar2 += "                                  <p style=\"color:#666666; font-weigh:bold; font-size:14px;\">$produit_prix_2$ €<\/p>";
strVar2 += "                                <\/font>";
strVar2 += "                              <\/td>";
strVar2 += "                              <td width=\"15\">&nbsp;<\/td>";
strVar2 += "                            <\/tr>";
strVar2 += "                          <\/tbody>";
strVar2 += "                        <\/table>";
strVar2 += "                      <\/td>";
strVar2 += "                    <\/tbody>";
strVar2 += "                  <\/table>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "         ";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td>";
strVar2 += "                  <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "";
strVar2 += "          <!--FOOTER-->";
strVar2 += "";
strVar2 += "          <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; background: white;\" width=\"600\">";
strVar2 += "            <tbody>";
strVar2 += "              <tr>";
strVar2 += "                <td width=\"600\">";
strVar2 += "                  <p style=\"text-align:center; color: black; font-size:12px;\">";
strVar2 += "                    19-21 RUE POISSONNIÈRE,<br \/>";
strVar2 += "                    75002, PARIS<br \/>";
strVar2 += "                    +33 1 85 08 21 21<br \/>";
strVar2 += "                    &nbsp;";
strVar2 += "                  <\/p>";
strVar2 += "                <\/td>";
strVar2 += "              <\/tr>";
strVar2 += "            <\/tbody>";
strVar2 += "          <\/table>";
strVar2 += "        <\/td>";
strVar2 += "      <\/tr>";
strVar2 += "    <\/tbody>";
strVar2 += "  <\/table>";
strVar2 += "";
strVar2 += "  <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"600\">";
strVar2 += "    <tbody>";
strVar2 += "      <tr>";
strVar2 += "        <td>";
strVar2 += "          <img alt=\"\" border=\"0\" height=\"20\" src=\"http:\/\/file.splio4.com\/6ZM\/BU\/LfhX\/spacer.gif\" style=\"display:block\" width=\"482\" \/>";
strVar2 += "        <\/td>";
strVar2 += "      <\/tr>";
strVar2 += "    <\/tbody>";
strVar2 += "  <\/table>";
strVar1 += "        <\/td>";
strVar1 += "      <\/tr>";
strVar1 += "    <\/tbody>";
strVar1 += "  <\/table>";
strVar1 += "";




/**
 * @license Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

// Register a templates definition set named "default".
CKEDITOR.addTemplates( 'default', {
	// The name of sub folder which hold the shortcut preview images of the
	// templates.
	imagesPath: CKEDITOR.getUrl( CKEDITOR.plugins.getPath( 'templates' ) + 'templates/images/' ),

	// The templates definitions.
	templates: [ {
		title: 'Template 1 article',
		image: 'template1.gif',
		description: '',
		html: strVar1
	},
	{
		title: 'Template 2 articles',
		image: 'template1.gif',
		description: '',
		html: strVar2
	},
 	]
} );
