<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

use Application\Sonata\UserBundle\Entity\User;

/**
 * UserModule
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserModuleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUserModules(User $user)
	{
		$qb = $this->createQueryBuilder('um')
				->leftJoin('um.module', 'm')
				->addSelect('m')
				->where('um.user = :user')
				->setParameter('user', $user)
		;

		$qb ->getQuery()
			->getResult();

		return $qb
			->getQuery()
			->getResult();
	}
}
